/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedList;
import java.awt.List;
import javax.swing.JOptionPane;
import modelo.Punto2D;
import modelo.Utilidades;
/**
 *
 * @author santiago.londono_men
 */
public class Uipunto extends javax.swing.JFrame  {

    LinkedList<Punto2D> listaPuntos = new LinkedList<>();
    
    LinkedList<Punto2D> listaBait = new LinkedList<>();
    
    LinkedList<Punto2D> listaConcate = new LinkedList<>();
    
    LinkedList<Punto2D> subLista = new LinkedList<>();
    
    
   

    /**
     * Creates new form UIpunto
     */
   public Uipunto() {
    initComponents();
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreacoordenada = new javax.swing.JTextArea();
        panelcoordenada = new javax.swing.JPanel();
        Guardar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        Concatenar = new javax.swing.JButton();
        Invertir = new javax.swing.JButton();
        sublista = new javax.swing.JButton();
        operar = new javax.swing.JButton();
        Guardar2 = new javax.swing.JButton();
        mostrarbait = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jTextArea1.setColumns(3);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Coordenadas Registradas");

        TextAreacoordenada.setColumns(3);
        TextAreacoordenada.setRows(5);
        jScrollPane2.setViewportView(TextAreacoordenada);

        panelcoordenada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelcoordenada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelcoordenadaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelcoordenadaLayout = new javax.swing.GroupLayout(panelcoordenada);
        panelcoordenada.setLayout(panelcoordenadaLayout);
        panelcoordenadaLayout.setHorizontalGroup(
            panelcoordenadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        panelcoordenadaLayout.setVerticalGroup(
            panelcoordenadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        Guardar.setText("Guardar Coordenadas");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        mostrar.setText("Mostrar Coordenadas");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        Concatenar.setText("Concatenar");
        Concatenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcatenarActionPerformed(evt);
            }
        });

        Invertir.setText("Invertir Lista");
        Invertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvertirActionPerformed(evt);
            }
        });

        sublista.setText("Obtener sublista");
        sublista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sublistaActionPerformed(evt);
            }
        });

        operar.setText("Busqueda");
        operar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operarActionPerformed(evt);
            }
        });

        Guardar2.setText("Guardar Coordenadas(bait)");
        Guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar2ActionPerformed(evt);
            }
        });

        mostrarbait.setText("Mostrar Coordenadas Bait");
        mostrarbait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarbaitActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelcoordenada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(13, 705, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(operar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(mostrarbait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sublista, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Invertir, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(15, 15, 15))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Concatenar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(panelcoordenada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Guardar)
                            .addComponent(Concatenar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Guardar2)
                            .addComponent(Salir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Invertir)
                            .addComponent(mostrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sublista)
                            .addComponent(mostrarbait))
                        .addGap(18, 18, 18)
                        .addComponent(operar)))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        
        boolean t=Utilidades.escribirCoordenadas(listaPuntos, "CoordenadasPuntos.txt");
        if(t){
            JOptionPane.showMessageDialog(rootPane, "Si se guardo el archivo");
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se guardo el archivo");
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
        
        TextAreacoordenada.setText(mostrarC(listaPuntos));
        
        
    }//GEN-LAST:event_mostrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ConcatenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcatenarActionPerformed
        listaConcate.addAll(listaBait);
        listaConcate.addAll(listaPuntos);
        TextAreacoordenada.setText(mostrarC(listaConcate));
        
    }//GEN-LAST:event_ConcatenarActionPerformed

    private void InvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvertirActionPerformed
        // Permite invertir los valores de una lista
        Collections.reverse(listaPuntos);
        TextAreacoordenada.setText(mostrarC(listaPuntos));
    }//GEN-LAST:event_InvertirActionPerformed

    private void sublistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sublistaActionPerformed
        subLista.addAll(listaConcate.subList(0, 6));
        
    }//GEN-LAST:event_sublistaActionPerformed

    private void operarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operarActionPerformed
        //permite buscar un elemento en nuestra linked list
        double coordXy = Double.parseDouble(JOptionPane.showInputDialog("Inserte la coordenada X: "));
        double coordxY = Double.parseDouble(JOptionPane.showInputDialog("Inserte la coordenada y: "));
        Punto2D objOperate = new Punto2D(coordXy, coordxY);
        if (listaPuntos.contains(objOperate)){
            System.out.println("La coordenada: " + objOperate + "se encuentra en la posicion: "+ listaPuntos.indexOf(objOperate));
        }else{ System.out.println("Este dato no se encuentre en la lista...");}
        
    }//GEN-LAST:event_operarActionPerformed

    private void Guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar2ActionPerformed
        boolean t=Utilidades.escribirCoordenadas(listaBait, "CoordenadasPuntos.txt");
        if(t){
            JOptionPane.showMessageDialog(rootPane, "Si se guardo el archivo");
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se guardo el archivo");
        }
    }//GEN-LAST:event_Guardar2ActionPerformed

    private void mostrarbaitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarbaitActionPerformed
        repaint();
        TextAreacoordenada.setText(mostrarC(listaBait));
    }//GEN-LAST:event_mostrarbaitActionPerformed

    private void panelcoordenadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcoordenadaMouseClicked
        // TODO add your handling code here:
        double coorX=evt.getX();
        double coorY=evt.getY();
        double coorXB;
        double coorYB;
        coorXB= coorY + 5;
        coorYB= coorX - 11;
        Punto2D objP = new Punto2D(coorX, coorY);
        Punto2D objPB = new Punto2D(coorXB, coorYB);
        listaPuntos.add(objP);
        listaBait.add(objPB);

    }//GEN-LAST:event_panelcoordenadaMouseClicked

    public String mostrarC(LinkedList<Punto2D> l){
        String mostrar1="";
        for (int i = 0; i < l.size(); i++) {
            Punto2D get = l.get(i);
            mostrar1+=get.toString()+"\n";
        }
        
        
        return mostrar1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uipunto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Concatenar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Guardar2;
    private javax.swing.JButton Invertir;
    private javax.swing.JButton Salir;
    private javax.swing.JTextArea TextAreacoordenada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton mostrar;
    private javax.swing.JButton mostrarbait;
    private javax.swing.JButton operar;
    private javax.swing.JPanel panelcoordenada;
    private javax.swing.JButton sublista;
    // End of variables declaration//GEN-END:variables

   
}

